config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'

    resources :sessions, only: [:create, :destroy]
    resource :home, only: [:show]

    root to: "home#show"
    
    get 'users/invitefriend/:id' => 'user#invitefriend'
    get '/update_location' => 'home#update_location'
    get '/distance' => 'home#distance'
    get '/searchlist' => 'home#searchlist'
    get 'searchfriends' => 'home#friendslist'
    get 'matchfriends' => 'home#matchfriends'
    get 'invite_mail' => 'home#invite_mail' 
    get 'messages' => 'home#messages'
    post 'invite_mail_send' => 'home#invite_mail_send'
    resources :conversations do
      resources :messages
    end

    get '/status/:status' => 'home#status'
    
    resources :users

end

app/views/shared/_footer.html.erb
<!--footer-start-->
<div class="footer navbar-fixed-bottom">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<div class="col-lg-4 col-md-4 col-sm-4">
				<%# abort params[:action].inspect %>
				<% if params[:action] == 'show' %>

						<%= link_to '<span> <i class="fa fa-5x fa-check-square-o"></i></span>'.html_safe, matchfriends_path %>
					<% else %>
						<%= link_to '<span> <i class="fa fa-5x fa-users"></i></span>'.html_safe, root_path %>
					<% end %>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4">
				<span>
				</span>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4">
				<% if session[:mark_messages] == 1  %>
					<%= link_to '<span> <i class="fa fa-5x fa-envelope-o redCls"></i></span>'.html_safe, messages_path %>
				<% else %>
					<%= link_to '<span> <i class="fa fa-5x fa-envelope-o"></i></span>'.html_safe, messages_path %>
				<% end %>
			</div>
		</div>
	</div>
</div>
<!--footer-end-->

app/views/shared/_header.html.erb
<!--header-start-->
<div class="header navbar-fixed-top">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<div class="col-lg-4 col-md-4 col-sm-4">
				<%= link_to '<span> <i class="fa fa-5x fa-search"></i></span>'.html_safe, searchlist_path %>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4">

				<span>
					<%= link_to image_tag("/images/hey1.png",  :class => "heyimg")%>
				</span>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4">
				<span>
					<% if params[:action] == 'invite_mail' %>
						<%= link_to '<span> <i class="fa fa-5x fa-sign-out"></i></span>'.html_safe, signout_path %>
					<% else %>
						<%= link_to '<span> <i class="fa fa-5x fa-wrench"></i></span>'.html_safe,  invite_mail_path %>
					<% end %>
				</span>
			</div>
		</div>            
	</div>
</div>

<!--header-end-->

app/views/shared/_search_header.html.erb
<!--header-start-->

<div class="header navbar-fixed-top">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<%= form_tag("/searchfriends", method: 'get', :remote => true) do %>
				  <div class="search">
				      <span class="fa fa-5x fa-search"></span>
				      <input type="search" class="form-control search-margin-top" name="searchFriend" id="searchFriend" placeholder="Search" />
				   </div>    
			  <% end %>
		</div>            
	</div>
</div>
<!--header-end-->

app/views/shared/_without_header.html.erb
<span>
	<%= link_to image_tag("/images/hey1.png",  :class => "heyimg heyfb")%>
</span>
<%= link_to image_tag("/images/fb1.png"), "/auth/facebook", id: "sign_in", class: "fb" %>