config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'

    resources :sessions, only: [:create, :destroy]
    resource :home, only: [:show]

    root to: "home#show"
    
    get 'users/invitefriend/:id' => 'user#invitefriend'
    get '/update_location' => 'home#update_location'
    get '/distance' => 'home#distance'
    get '/searchlist' => 'home#searchlist'
    get 'searchfriends' => 'home#friendslist'
    get 'matchfriends' => 'home#matchfriends'
    get 'invite_mail' => 'home#invite_mail' 
    get 'messages' => 'home#messages'
    post 'invite_mail_send' => 'home#invite_mail_send'
    resources :conversations do
      resources :messages
    end

    get '/status/:status' => 'home#status'
    
    resources :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :login_user, :only => [:searchlist, :distance, :matchfriends]
	respond_to :html, :js
	include HomeHelper
	helper_method :dist
	 
	def show

		if current_user
			
			@user_fb_token = current_user.oauth_token
			@friendsHash = Hash.new()
			unless @user_fb_token.blank?
				@fb_friends = FbGraph::User.me(@user_fb_token).friends
				@fb_friends = @fb_friends.sort_by { |fb_frnd| fb_frnd.raw_attributes['name']}
				if @fb_friends
					@fb_friends.each do |frd|
						@friendsHash[frd.raw_attributes['id'].to_s] = frd.raw_attributes['name']
					end
				end
			end

			# Save frieds hash array into database - serialization
			current_user.multi_friends = @friendsHash
			current_user.save

			# Get current user invited friends
			inviteFriends
			@alreadyinvitedusers = []
			if !@invitedFriends.blank?
				@invitedFriends = @invitedFriends.map(&:inspect).join(', ')
				@alreadyinvitedusers = User.where("id in (#{@invitedFriends})").pluck(:uid)
			end

			# Get user Accepted friends UID
			acceptedFriends
			@alreadyAcceptedUsers = []
			if !@acceptedFriends.blank?
				@acceptedFriends = @acceptedFriends.map(&:inspect).join(', ')
				@alreadyAcceptedUsers = User.where("id in (#{@acceptedFriends})").pluck(:uid)
			end

            @dt = {}
            current_user.multi_friends.each do |k,v| 
            	dist = dist(k)
            	dist = (dist == 'No found') ? 99999 : dist
                @dt.merge!( k => dist)
            end
            @sortFriends = @dt.sort_by {|_k, val| val}
            
		end
	end

	# Search page for friends
	def searchlist
		@friendsHash = current_user.multi_friends
		# Get current user invited friends
		inviteFriends
		@alreadyinvitedusers = []
		if !@invitedFriends.blank?
			@invitedFriends = @invitedFriends.map(&:inspect).join(', ')
			@alreadyinvitedusers = User.where("id in (#{@invitedFriends})").pluck(:uid)
		end

		# Get user Accepted friends UID
		acceptedFriends
		@alreadyAcceptedUsers = []
		if !@acceptedFriends.blank?
			@acceptedFriends = @acceptedFriends.map(&:inspect).join(', ')
			@alreadyAcceptedUsers = User.where("id in (#{@acceptedFriends})").pluck(:uid)
		end
		
		@dt = {}
        current_user.multi_friends.each do |k,v| 
            dist = dist(k)
        	dist = (dist == 'No found') ? 99999 : dist
            @dt.merge!( k => dist)
        end

        @sortFriends = @dt.sort_by {|_k, val| val}
	end

    def update_location
	    current_user.update_attributes(:latitude => params[:lat], :longitude => params[:lon])
	    render nothing: true
    end

	def distance 
     
	end	

	def invite_mail_send
		if params[:invite] and !params[:invite][:email].blank?
			appUrl = root_url
			name = current_user.name
			UserMailer.welcome_email(params[:invite][:email],appUrl, name).deliver_later
			redirect_to invite_mail_path, :notice => "Successfully sent invitation."
		else 
			redirect_to request.referer, :notice => "Something went wrong. Please try again later."
		end
	end

	def messages
		@conversations = Conversation.involving(current_user).order("created_at DESC")
	end

	# Match friends list
	def matchfriends
		
		acceptedFriends

		@alreadyinvitedusers = []
		@dt = {}
		if !@acceptedFriends.blank?
			@acceptedFriends = @acceptedFriends.map(&:inspect).join(', ')
			@alreadyinvitedusers = User.where("id in (#{@acceptedFriends})")
			@alreadyinvitedusers.each do |v| 
                dist = dist(v.uid)
	        	dist = (dist == 'No found') ? 99999 : dist
	            @dt.merge!( v.id => dist)
            end
		end
    	
	end

  	def friendslist
  		if params[:searchFriend]
  			@friendsHash = current_user.multi_friends

  			# Get current user invited friends
  			inviteFriends
  			@alreadyinvitedusers = []
			if !@invitedFriends.blank?
				@invitedFriends = @invitedFriends.map(&:inspect).join(', ')
				@alreadyinvitedusers = User.where("id in (#{@invitedFriends})").pluck(:uid)
			end

			# Get user Accepted friends UID
			acceptedFriends
			@alreadyAcceptedUsers = []
			if !@acceptedFriends.blank?
				@acceptedFriends = @acceptedFriends.map(&:inspect).join(', ')
				@alreadyAcceptedUsers = User.where("id in (#{@acceptedFriends})").pluck(:uid)
			end

			@friendsHash = @friendsHash.select{|key, hash| hash.downcase.include?(params[:searchFriend].downcase) }

			@dt = {}
            @friendsHash.each do |k,v| 
                dist = dist(k)
	        	dist = (dist == 'No found') ? 99999 : dist
	            @dt.merge!( k => dist)
            end

            @sortFriends = @dt.sort_by {|_k, val| val}
  		end
  	end

  	def status
      	session[:status] = params[:status]
      	render nothing: true
  	end

  	
end

app/helpers/home_helper.rb
module HomeHelper
	def to_rad(angle)
       angle * Math::PI / 180 
    end

 
	def dist(fbid)
		@me_latitude = current_user.latitude
		@me_longitude = current_user.longitude
		
		# @friendsHash.each do |item|
			if !@me_latitude.nil?
				@friendDetail = User.find_by_uid(fbid)

				# abort @friendDetail.latitude.inspect				
				if @friendDetail and !@friendDetail.latitude.nil?
					@frd_latitude = @friendDetail.latitude
					@frd_longitude = @friendDetail.longitude
					
					radius = 6371
				    lat1 = self.to_rad(@me_latitude)
				    lat2 = to_rad(@frd_latitude)
				    lon1 = to_rad(@me_longitude)
				    lon2 = to_rad(@frd_longitude)
				    dLat = lat2-lat1  
				    dLon = lon2-lon1
				    a = Math::sin(dLat/2) * Math::sin(dLat/2) +
				       Math::cos(lat1) * Math::cos(lat2) * 
				       Math::sin(dLon/2) * Math::sin(dLon/2);
				    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a));
				    @d = (radius * c).round
				else
					@d = 'No found'
				end
			else
				@d = 'No found'
			end	
		# end	
		# @dt = []
		# @dt << @d 
		# abort @dt.inspect
	    return @d
    end

    def times(id)
    	@invitedFriendDate = Invitefriend.select("created_at").where("(user_id = #{current_user.id} and inviteid = #{id}) OR (user_id = #{id} and (inviteid = #{current_user.id} or invite_accepted = true))")
       # @c = ((Time.now - @invitedFriendDate[0].created_at)/60 ).to_i
        @c = ((Time.now.in_time_zone("Pacific Time (US & Canada)") - @invitedFriendDate[0].created_at)/60 ).to_i
		return @c.to_s
	end

	def conversation_interlocutor(conversation)
    	conversation.recipient == current_user ? conversation.sender : conversation.recipient
  	end
end

app/views/home/_friendslist.html.erb
<div class="middle">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 friendfb">
			  	<% if @friendsHash.count > 0 %>
			  		<% @sortFriends.each do |item| %>			  		
				  			<% @classphoto =  (@alreadyinvitedusers.include? item[0]) ? "fb-invited" : "fb-photo" %>
				  			<% @classphoto =  (@alreadyAcceptedUsers.include? item[0]) ? "fb-invited fb-accepted" : @classphoto %>

				          	<div class="col-lg-4 col-md-4 col-sm-4">
				          		<% if @classphoto == "fb-invited fb-accepted" %>
				          			
				          				<%
								  			@u1 = User.where("uid = (?)", item[0]).pluck(:id)
								  		    @convFriends = Conversation.where("((sender_id IN (?) and recipient_id IN (?)) OR (sender_id IN (?) and recipient_id IN (?))) ", @u1[0], current_user.id, current_user.id, @u1[0])
								  		%>

								  	<div class="image polaroid tint2 tint1" data-id="<%=@u1[0]%>">
				          				<%= link_to image_tag("http://graph.facebook.com/#{item[0]}/picture?type=large"),  conversation_path(@convFriends[0]), class: "float-left conversation conversation#{@u1[0]}", "data-cid" => @convFriends[0].id %>

				          		<% elsif @classphoto == "fb-invited" %>
				          			<div class="image polaroid tint">
				          				<div class="imgReplace"><%= image_tag "http://graph.facebook.com/#{item[0]}/picture?type=large", :class => "float-left #{@classphoto}", :id => item[0] %></div>
				          	 	<% else %>		
				          			<div class="image polaroid">
				          				<div class="imgReplace"><%= image_tag "http://graph.facebook.com/#{item[0]}/picture?type=large", :class => "float-left #{@classphoto}", :id => item[0] %></div>
				          		<% end %>	
									<div class='desc' id="fb_name_<%= item[0]%>">
										<%= @friendsHash[item[0]] %></br>
										<%# if !session[:status] || session[:status] == "true" %>	
											<%= (item[1] == 99999) ? "Not Shared Miles" : item[1].to_s + " Miles Away" %>
										<%# end %>
									</div>
								</div>								
						    </div>
						<% end %>    
			    <% else %>
			    <div class="mess">
			    	<center><p class="text-info">No friends found in your account.</p></center>
			    	<%= link_to 'Click here to invite friends'.html_safe, invite_mail_path %>
			    </div>
			    <% end %>
		</div>
	</div>
</div>

app/views/home/distance.html.erb
<table width="100%" class="table">
  	<tbody>
	  	<tr>
	  	<% if current_user.multi_friends %>
	  		<% current_user.multi_friends.each do |item| %>
		  		<tr class="a1">
		          	<div class="row">
			      		<div class='fb-avatar-section'>
				      		<!-- <td width="33%"> -->
						        <div class="alignment "><td width="13%">
						        	<%= image_tag "http://graph.facebook.com/#{item[0]}/picture", :class => "float-left #{@classphoto}", :id => item[0] %></td><td>
										<div class='float-left fb-avatar-desc'>
										  <div class="a11">
											<div class='float-left full-width fb-avatar-name' id="fb_name_<%= item[0]%>" style="font-family: bold">
												<%= item[1] %></br>
												<%= dist(item[0]) %>&nbsp;&nbsp;<span>Miles Away</span>
                                             
											</div>
										  </div>
										<div></td>							
						        </div>
					       	<!-- </td> -->
						</div>
					</div>	
				</tr>
	      	<% end %>
	    <% else %>
	    	No friends found in your account.
	    <% end %>
	</tr>
  	</tbody>
</table>

app/views/home/friendslist.js.erb
$('#friendslist').html("<%= escape_javascript (render partial: 'friendslist') %>");

app/views/home/invite_mail.html.erb
<div class="container">
	<div class="invitation">
		
            <center><p class="text-info heading_message", style="text-align: center;"><b>What is Hey ?</b></br></p></center>
<center><p class="text-info reset_message">
Hey! makes it easier for you to hang out with the people you know close by. There's no need to ask them if they're free or try to make plans for the future. Just select the friends you want to hang out with right now. If they selected you too, you will both be notified. If not, nobody will ever know. You will only know who wants to hang out with you if you want to hang out with them too. Selections reset every two hours.</p></center>

<%= form_for :invite, url: invite_mail_send_path , html: {:id => 'invite_mail'},  validate: true do |f| %>
<center><p class="text-info invitition">Invite your friends!</p></center>

			<div class="form-group" style="width:100%;">
				<div class="field">
					<%= f.email_field :email, :placeholder => " Friend Email", required: :require, :size => 10, :id => 'valid', :class => 'form-control-invite', :style => "float:left;"  %>
					<%= f.submit "Send", class: "btn btn-lg btn-primary", :style => "float:left; line-height:0.7; margin-left:5px;" %>
				</div>
			</div></br></br>
			
			<div class="actions">
				&nbsp;
			</div>
		<% end %>
	</div>
</div>

<% if current_user %>

<script>
	$(document).on('click', '.onoffswitch-checkbox', function() {
	    $(this).toggleClass('toggle-button-selected');
	    // var status = false;
	    if($(".onoffswitch-checkbox").is(":checked")== true)
		    {

		    $.ajax({
		  		url: '/status/'+ $(".onoffswitch-checkbox").is(":checked"),
				});

		    // if(status == true) {
			    function getLocation() {
				  if (navigator.geolocation) {
				      navigator.geolocation.getCurrentPosition(showPosition);
				  } else { 
				      x.innerHTML = "Geolocation is not supported by this browser.";
				  }
				}

				function showPosition(position) {
				  //x.innerHTML = "Latitude: " + position.coords.latitude + 
				 //"<br>Longitude: " + position.coords.longitude;
				  var data = { 'lat': position.coords.latitude, 'lon': position.coords.longitude }; 
				  $.ajax({
				      type: 'GET', 
				      url: '/update_location',
				      data: data
				  });
				}

				getLocation();
			//}
		}
    	$.ajax({
	  		url: '/status/'+ $(".onoffswitch-checkbox").is(":checked"),
		});
	});
	</script>

<% end %>

app/views/home/matchfriends.html.erb
<div class="container" style="margin-top: 2% !important;">
  <div class="row">
    <div class="col-xs-12">
      <div class="table-responsive" id="friendslist">
				<div class="middle">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12">
							  	<% if @alreadyinvitedusers.count > 0 %>
							  		<% @alreadyinvitedusers.each do |item| %>
								  			<% 
									  			@convFriends = Conversation.where("((sender_id IN (?) and recipient_id IN (?)) OR (sender_id IN (?) and recipient_id IN (?))) ", item.id, current_user.id, current_user.id, item.id)
				      		  		%>
								          	<div class="col-lg-4 col-md-4 col-sm-4">
								          		<div class="image polaroid tint2 tint1" data-id="<%=item.id%>">
									          		<%= link_to image_tag("http://graph.facebook.com/#{item.uid}/picture?type=large"),  conversation_path(@convFriends[0]), class: "float-left conversation conversation#{item.id}", "data-cid" => @convFriends[0].id %>
																<div class='desc' id="fb_name_<%= item[0]%>">
																	<%= item.name %></br>
																	<%=times(item.id) %> Mins <br>
																	<%# if session[:status] and session[:status] == "true" %>
																	<%# if !session[:status] || session[:status] == "true" %>
																		<%= (@dt[item.id] == 99999) ? "Not Shared Miles" : @dt[item.id].to_s + " Miles Away" %>
																	<%# end %>
																</div>
															</div>	
														</div>								
										<% end %>    
							    <% else %>
							    <div class="mess">
							    	
							    	<center><p class="text-info" >No friends matched.</p></center>
							    </div>
							    <% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
(function a() {
    $(".tint1").click(function(e){
    	if($(e.target).is('.tint1')){
	  		var cid = $(this).attr("data-id");
	  		$(".conversation"+cid).click();
	  	}
  	});
})();
</script>

app/views/home/messages.html.erb
<div style="height: auto; overflow-y: hidden;">
  
  <% if @conversations.any? %>

      <ul class="media-list">
          <% @conversations.each do |conversation| %>
            <li class="media">
              <%= link_to image_tag("http://graph.facebook.com/#{conversation_interlocutor(conversation).uid}/picture?type=large"),  conversation_path(conversation), class: "float-left #{@classphoto} conversation", "data-cid" => conversation.id %>
              <div class="media-body">
                    <h4 class="media-heading"><%= link_to conversation_interlocutor(conversation).name, conversation_path(conversation), class: "conversation", style: "color:#000;", "data-cid" => conversation.id %></h4>
                    <% last_message = conversation.messages.last.nil? ? "No messages." : truncate(conversation.messages.last.body, length: 45) %>
                    <p><%= link_to last_message, conversation_path(conversation), class: "conversation", style: "color:#000;", "data-cid" => conversation.id %></p>
              </div>
            </li>
          <% end %>
      </ul>
  <% else %>
      
       <center><p class="text-info mess">You have no conversations. Conversations will automatically start after matching with a friend.</p></center>

  <% end %>
   
</div>

app/views/home/searchlist.html.erb
<div class="container" style="margin-top: 6%;">
  <div class="row">
    <div class="col-xs-12">
      <div class="table-responsive" id="friendslist">
        <% if current_user %>
          <%= render 'friendslist' %>
        <% end %>
      </div><!--end of .table-responsive-->
    </div>
  </div>
</div>

<script>
$( document ).ready(function() {
	// <!-- Form submit after write more than 2 char or none -->
    $('#searchFriend').keyup(function(e) {
    	var existingString = $("#searchFriend").val();
    	if (existingString.length < 2 && existingString.length>0) return;
	    $('#searchFriend').submit();
	});
});
</script>

app/views/home/show.html.erb
<%#= form_tag("/searchfriends", method: 'get', :remote => true) do %>
     <!--  <input type="search" class="form-control search-margin-top" name="searchFriend" id="searchFriend" placeholder="Search" /> -->
    <%# end %>
<div class="" style="margin-top: 2% !important;">
  <div class="row">
    <div class="col-xs-12">
      <div class="table-responsive" id="friendslist">
        <% if current_user %>
          <%= render 'friendslist' %>
        <% end %>
      </div><!--end of .table-responsive-->
    </div>
  </div>
</div>

<% if current_user %>
  <script type="text/javascript">
    $(function(){
      // var x = document.getElementById("demo");
      getLocation();
      function getLocation() {
        
          if (navigator.geolocation) {
              navigator.geolocation.getCurrentPosition(showPosition);
          } else { 
              x.innerHTML = "Geolocation is not supported by this browser.";
          }
        }

      function showPosition(position) {
          //x.innerHTML = "Latitude: " + position.coords.latitude + 
         //"<br>Longitude: " + position.coords.longitude;
          var data = { 'lat': position.coords.latitude, 'lon': position.coords.longitude }; 
          $.ajax({
              type: 'GET', 
              url: '/update_location',
              data: data
          });
        }

      $(document).on('click', '.tint1', function(e){ 
        if($(e.target).is('.tint1')){ 
          var cid = $(this).attr("data-id");
          $(this).find(".conversation").click();
          // $(".conversation"+cid).click();
        }
      });

    });
  </script>
<% end %>